#!/bin/bash
set -e

mysql -u root -p$MYSQL_ROOT_PASSWORD <<EOSQL
CREATE USER IF NOT EXISTS '$MYSQL_USER_1'@'%' IDENTIFIED BY '$MYSQL_PASSWORD_1';
GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_USER_1'@'%' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS '$MYSQL_USER_2'@'%' IDENTIFIED BY '$MYSQL_PASSWORD_2';
GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_USER_2'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
EOSQL
